[package]
name = "omega_san"
version = "0.1.0"
authors = ["Kyle Clemens <jkc.clemens@gmail.com>"]

[dependencies]
discord = { version = "*", git = "https://github.com/jkcclemens/discord-rs" }
dotenv = "0.10"
regex = "0.2"
lazy_static = "0.2"
